### ISSUE TITLE
How to choose EX-Kurayami?

### ISSUE THREAD

**Issue by EDTmagiclab** [Maxmani/touhou-origins#15]
I can't find anything about it in language text

**Comment by wasakoki** [comment]
the fun answer:  you don't choose EX-Kurayami, instead, EX-Kurayami chooses you.

the real answer:  EX-Kurayami can't be chosen or upgraded into, instead it is something that Kurayami have a chance to randomly become during the right conditions. since the origin is temporary and the chance is very rare i decided not to add mention of it in game and instead more as a hidden feature/easter egg of the origin.

Currently the "right conditions" to have a chance at becoming EX-Kurayami is to be under moonlight during the night time and to either be wearing fire protection armor (more levels = better chance) or to be under the effects of the fire resistance status effect

**Comment by EDTmagiclab** [comment]
> the fun answer: you don't choose EX-Kurayami, instead, EX-Kurayami chooses you.
> 
> the real answer: EX-Kurayami can't be chosen or upgraded into, instead it is something that Kurayami have a chance to randomly become during the right conditions. since the origin is temporary and the chance is very rare i decided not to add mention of it in game and instead more as a hidden feature/easter egg of the origin.
> 
> Currently the "right conditions" to have a chance at becoming EX-Kurayami is to be under moonlight during the night time and to either be wearing fire protection armor (more levels = better chance) or to be under the effects of the fire resistance status effect

Wow,really a cool design!I like this idea.
